import { resolvePublicAssetUrl } from "./asset-url";
import type { CardDefinition } from "./types";

/**
 * Tokens whose arrival is the result of a Deathrattle or a passive death
 * trigger. These are the only temporary minions with their own YouTube theme;
 * Battlecry and Hero-Power tokens deliberately stay on the generic summon FX.
 */
export const TOKEN_THEME_IDS = [
  "token:shenron",
  "token:morgott",
  "token:drakath",
  "token:vision",
  "token:galactus",
  "token:awakened",
  "token:larva",
] as const;

export function isThemedTokenId(cardId: string): boolean {
  return (TOKEN_THEME_IDS as readonly string[]).includes(cardId);
}

/**
 * Board-created minions are not part of the collectible roster, but they are
 * still real playable cards when an effect returns one to hand. Keeping their
 * definitions here gives the engine and UI one source of truth without adding
 * tokens to the deck, unlock track, or card gallery.
 */
export const TOKEN_CARDS: CardDefinition[] = [
  {
    kind: "minion",
    id: "token:shenron",
    name: "Shenron",
    cost: 7,
    atk: 7,
    hp: 7,
    rarity: "Black",
    camp: "Magic",
    alignment: "Neutral",
    keywords: ["Taunt"],
    effectId: "none",
    effectTiming: "none",
    effect: "Taunt.",
    flavor: "The wish dragon answers.",
    origin: "Dragon Ball",
    art: resolvePublicAssetUrl("/card-art/raw/token-shenron.webp"),
  },
  {
    kind: "minion",
    id: "token:knight",
    name: "Knight",
    cost: 0,
    atk: 1,
    hp: 1,
    rarity: "Black",
    camp: "Magic",
    alignment: "Good",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "A small spark can turn the tide.",
    origin: "Hero Power",
    art: resolvePublicAssetUrl("/card-art/raw/token-knight.webp"),
  },
  {
    kind: "minion",
    id: "token:shadow-clone",
    name: "Shadow Clone",
    cost: 0,
    atk: 2,
    hp: 2,
    rarity: "Black",
    camp: "Magic",
    alignment: "Good",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "One body becomes many.",
    origin: "Naruto",
    art: resolvePublicAssetUrl("/card-art/raw/token-shadow-clone.webp"),
  },
  {
    kind: "minion",
    id: "token:larva",
    name: "Larva",
    cost: 0,
    atk: 1,
    hp: 1,
    rarity: "Black",
    camp: "Nature",
    alignment: "Evil",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "One more for the hive.",
    origin: "Alien",
    art: resolvePublicAssetUrl("/card-art/raw/token-larva.webp"),
  },
  {
    kind: "minion",
    id: "token:sin",
    name: "Sin",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "Black",
    camp: "Magic",
    alignment: "Evil",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "A fragment of sin.",
    origin: "The Seven Deadly Sins",
    art: resolvePublicAssetUrl("/card-art/raw/token-sin.webp"),
  },
  {
    kind: "minion",
    id: "token:tie-fighter",
    name: "TIE Fighter",
    cost: 1,
    atk: 1,
    hp: 1,
    rarity: "Black",
    camp: "Tech",
    alignment: "Evil",
    keywords: ["Charge"],
    effectId: "none",
    effectTiming: "none",
    effect: "Charge.",
    flavor: "Twin ion engines scream through the void.",
    origin: "Star Wars",
    art: resolvePublicAssetUrl("/card-art/raw/token-tie-fighter.webp"),
  },
  {
    kind: "minion",
    id: "token:morgott",
    name: "Morgott, the Omen King",
    cost: 3,
    atk: 3,
    hp: 3,
    rarity: "Black",
    camp: "Nature",
    alignment: "Evil",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "The omen king returns.",
    origin: "Elden Ring",
    art: resolvePublicAssetUrl("/card-art/raw/token-morgott.webp"),
  },
  {
    kind: "minion",
    id: "token:drakath",
    name: "Drakath",
    cost: 5,
    atk: 5,
    hp: 3,
    rarity: "Black",
    camp: "Magic",
    alignment: "Evil",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "Chaos answers chaos.",
    origin: "AdventureQuest Worlds",
    art: resolvePublicAssetUrl("/card-art/raw/token-drakath.webp"),
  },
  {
    kind: "minion",
    id: "token:vision",
    name: "Vision",
    cost: 7,
    atk: 5,
    hp: 3,
    rarity: "Purple",
    camp: "Tech",
    alignment: "Good",
    keywords: ["Taunt"],
    effectId: "none",
    effectTiming: "none",
    effect: "Taunt.",
    flavor: "Built to end him. Chose otherwise.",
    origin: "MCU",
    art: resolvePublicAssetUrl("/card-art/raw/token-vision.webp"),
  },
  {
    kind: "minion",
    id: "token:galactus",
    name: "Galactus",
    cost: 5,
    atk: 8,
    hp: 8,
    rarity: "Black",
    camp: "Magic",
    alignment: "Neutral",
    keywords: ["Taunt", "Cannot Attack"],
    effectId: "none",
    effectTiming: "none",
    effect: "Taunt. Cannot attack.",
    flavor: "The devourer of worlds arrives.",
    origin: "Marvel",
    art: resolvePublicAssetUrl("/card-art/raw/galactus.webp"),
  },
  {
    kind: "minion",
    id: "token:awakened",
    name: "Awakened",
    cost: 6,
    atk: 6,
    hp: 3,
    rarity: "Red",
    camp: "Magic",
    alignment: "Good",
    keywords: [],
    effectId: "none",
    effectTiming: "none",
    effect: "-",
    flavor: "The Avatar's spirit wakes.",
    origin: "Avatar",
    art: resolvePublicAssetUrl("/card-art/raw/token-awakened.webp"),
  },
];

const TOKEN_BY_ID = Object.fromEntries(TOKEN_CARDS.map((card) => [card.id, card]));

/** Returns a fresh token definition, optionally with summon-specific metadata. */
export function tokenCard(id: string, overrides: Partial<CardDefinition> = {}): CardDefinition {
  const base = TOKEN_BY_ID[id];
  if (!base) throw new Error(`Unknown token card: ${id}`);
  return {
    ...base,
    ...overrides,
    keywords: [...(overrides.keywords ?? base.keywords)],
  };
}

export function isTokenCardId(cardId: string): boolean {
  return cardId.startsWith("token:");
}
