/** Production-only smoke: no source imports or development hooks in the browser. */
import { launch, settleMotion } from './browser.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { skipCampaignDialogue } from './story-fixtures.mjs';
import { manualRotationBrowser, resizePhone, rotateForDuel } from './phone-fixtures.mjs';
import { checkCampaignMotion } from './campaign-motion.mjs';
import { confirmStarterRestore } from './deck-fixtures.mjs';
import { checkDeckHover, checkGalleryHold, checkFastGalleryScroll, checkPreviewFallback } from './gallery-interactions.mjs';
const base=process.argv[2];if(!base)throw new Error('Pass the published /play/ URL');
const browser=await launch();const page=await browser.newPage({viewport:{width:1440,height:950}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const progress=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('convergence.progress.v4')));
try{
 await mkdir('../.preview/release',{recursive:true});
 await page.goto(base,{waitUntil:'domcontentloaded'});
 await page.evaluate(()=>{localStorage.clear();localStorage.setItem('convergence.progress.v2','{"unlocked":216}');localStorage.setItem('convergence.save.v27','{"version":27}');localStorage.setItem('sound-test-preference','preserved');});
 await page.reload();await page.locator('.title-screen').waitFor();
 assert.equal(await page.locator('.hero-power-trigger').count(),0);
 assert.equal((await progress()).unlockedIds.length,40);assert.equal((await progress()).completedChapters,0);
 assert.equal(await page.locator('.orbit-choice,.daily-pack-trigger').count(),0);
 assert.equal(await page.evaluate(()=>localStorage.getItem('convergence.progress.v2')),null);
 assert.equal(await page.evaluate(()=>localStorage.getItem('sound-test-preference')),'preserved');
 await page.keyboard.type('Ross');await page.locator('.duel-trigger').click();
 assert.equal(await page.locator('.campaign-chapter').count(),20);
 await page.locator('[data-chapter="1"] button').click();
 await page.locator('[data-story-key]').waitFor(); await skipCampaignDialogue(page);
 await page.locator('.duel-intro').waitFor({state:'detached',timeout:25000});
 await page.locator('.mulligan-panel button.primary').click();
 await page.locator('.boss-portrait').evaluate(img=>img.decode());
 assert.equal(await page.evaluate(()=>typeof window.__debug),'undefined');
 assert((await page.locator('.campaign-hero .hero-name strong').textContent()).includes('GLaDOS'));
 await page.getByRole('button',{name:'Open Star Chart for GLaDOS',exact:true}).click();
 assert(await page.getByRole('dialog',{name:'GLaDOS Star Chart',exact:true}).isVisible());
 await page.getByLabel('Close Star Chart').click();
 await page.screenshot({path:'../.preview/release/live-chapter-one.png'});
 await page.getByRole('button',{name:'DEV tools',exact:true}).click();
 await page.locator('.developer-search input').fill('John Wick');await page.locator('.developer-card-row').first().click();
 await page.getByRole('button',{name:'I win',exact:true}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('convergence.progress.v4')).completedChapters===1);
 assert.equal((await progress()).unlockedIds.length,49);assert.equal((await progress()).pendingRewards.length,9);
 await page.reload();await page.locator('[data-story-stage="defeat"]').waitFor();await skipCampaignDialogue(page);await page.locator('.pack-veil').waitFor();assert.equal((await progress()).pendingRewards.length,9);
 await settleMotion(page);
 for(let hit=0;hit<8;hit++){const box=page.locator('.pack-box:not(.is-charged)');if(!await box.isVisible())break;const label=await box.getAttribute('aria-label');await box.click({force:true});await page.waitForFunction(label=>document.querySelector('.pack-box')?.getAttribute('aria-label')!==label,label);}
 await page.locator('.pack-collect:not([disabled])').click({timeout:25000});
 await page.locator('.deck-trigger').click();await page.locator('.gallery-cell').first().waitFor();await checkDeckHover(page);
 assert((await page.locator('.gallery-hero-power').textContent()).includes('New hero power available'));
 await page.getByRole('button',{name:'Choose hero power',exact:true}).click();await page.getByLabel('Close hero power chooser').click();
 assert.equal(await page.locator('.gallery-hero-power.has-new-power').count(),0);
 assert.equal(await page.locator('.gallery-deck-badge').count(),30,'Published membership badges are missing');
 await page.getByRole('button',{name:'Remove John Wick from deck',exact:true}).click();
 await page.getByLabel('Search the gallery').fill('GLaDOS');await page.getByRole('button',{name:'Add GLaDOS',exact:true}).click();
 assert.equal((await progress()).playerDeck.length,30);assert((await progress()).playerDeck.includes('c104'));
 await page.getByRole('button',{name:'Choose hero power',exact:true}).click();
 assert((await page.locator('.hero-power-menu-intro').textContent()).includes('Conquer any universe'));
 assert.equal(await page.locator('.hero-power-menu-note').count(),0);
 assert.equal(await page.locator('.gallery-power-picker .hero-power-menu-card:not(:disabled)').count(),1);
 await page.locator('.gallery-power-picker .hero-power-menu-card').filter({hasText:'Mend Core'}).click();
 assert.equal((await progress()).selectedHeroPower,'core_heal');
 await page.reload();assert((await progress()).playerDeck.includes('c104'));assert.equal((await progress()).pendingRewards.length,0);
 await page.locator('.duel-trigger').click();assert(await page.locator('[data-chapter="2"] button').isEnabled());
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'../.preview/release/live-campaign-mobile.png'});
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await manualRotationBrowser(phoneContext);
 const phone=await phoneContext.newPage();phone.on('pageerror',error=>errors.push(error.message));
 await phone.goto(base,{waitUntil:'domcontentloaded'});
 await phone.locator('.deck-trigger').tap();
 await phone.locator('.gallery-cell .card-face').first().waitFor();
 await checkGalleryHold(phone);
 await checkFastGalleryScroll(phone);
 assert(await phone.getByLabel('Filter by mana',{exact:true}).isVisible(),'Published filters are hidden');
 assert(await phone.locator('.gallery-cell .card-face:not(.cf-blank) .cf-desc').evaluateAll(elements=>elements.length>0&&elements.every(el=>getComputedStyle(el).display!=='none')), 'Published collection descriptions are hidden');
 const collection=await phone.locator('.gallery-deck-card').evaluateAll(items=>items.slice(0,2).map(item=>{const r=item.getBoundingClientRect();return {x:r.x,y:r.y};}));
 assert(collection[1].x>collection[0].x && Math.abs(collection[1].y-collection[0].y)<1,'Published collection is not a grid');
 await phone.locator('.gallery-mobile-scroll').evaluate(el=>el.scrollTo({top:350}));
 assert(await phone.locator('.gallery-search').evaluate(el=>el.getBoundingClientRect().bottom<0),'Published collection header remains pinned');
 await phone.screenshot({path:'../.preview/release/live-phone-collection.png'});
 await phone.getByRole('button',{name:'Deck · 30/30',exact:true}).tap();
 await phone.getByRole('button',{name:'Remove John Wick from deck',exact:true}).tap();
 await phone.getByRole('button',{name:'Restore starter deck',exact:true}).tap();
 assert.equal(await phone.locator('.gallery-deck-row').count(),29,'Published reset happened without confirmation');
 await phone.getByRole('dialog',{name:'Restore starter deck?',exact:true}).getByRole('button',{name:'Cancel',exact:true}).tap();
 assert.equal(await phone.locator('.gallery-deck-row').count(),29,'Published Cancel changed the deck');
 await phone.getByRole('button',{name:'Restore starter deck',exact:true}).tap();await confirmStarterRestore(phone,true);
 assert.equal(await phone.locator('.gallery-deck-row').count(),30);
 await phone.screenshot({path:'../.preview/release/live-phone-deck.png'});
 await phone.getByRole('button',{name:'Close',exact:true}).tap();
 await phone.locator('.duel-trigger').tap();await checkCampaignMotion(phone);
 await phone.locator('[data-chapter="1"] button').tap();await skipCampaignDialogue(phone);
 await rotateForDuel(phone,390,844);
 await phone.locator('.duel-intro').dblclick();await phone.locator('.duel-intro').waitFor({state:'detached',timeout:25000});
 assert(await phone.locator('.mulligan-panel').evaluate(el=>el.scrollHeight<=el.clientHeight+1),'Published opening hand requires scrolling');
 await phone.locator('.mulligan-panel button.primary').tap();
 assert.equal(await phone.evaluate(()=>typeof window.__debug),'undefined');
 assert.equal(await phone.locator('.mobile-card-read').count(),0);
 assert(await phone.locator('.hand-card .card-face:not(.cf-blank) .cf-desc').evaluateAll(elements=>elements.every(el=>getComputedStyle(el).display!=='none')), 'Published hand cards hide their descriptions');
 await phone.getByRole('button',{name:'Duel menu',exact:true}).tap();
 assert.equal(await phone.getByRole('button',{name:'Undo last action',exact:true}).count(),0);
 await phone.getByRole('button',{name:'Duel menu',exact:true}).tap();
 const turnBefore=await phone.locator('.deck-pile em').textContent();
 await resizePhone(phone,390,844);await phone.getByRole('dialog',{name:'Landscape mode required',exact:true}).waitFor();
 await phone.screenshot({path:'../.preview/release/live-phone-rotate.png'});
 await phone.keyboard.press('Space');await phone.waitForTimeout(1100);
 assert.equal(await phone.locator('.deck-pile em').textContent(),turnBefore,'Portrait gate allowed a turn to advance');
 await resizePhone(phone,844,390);await phone.getByRole('dialog',{name:'Landscape mode required',exact:true}).waitFor({state:'detached'});
 await phone.screenshot({path:'../.preview/release/live-phone-duel.png'});
 await phoneContext.close();
 await checkPreviewFallback(browser,base);
 assert.deepEqual(errors,[]);
 console.log('PASS live production: old-save reset, campaign, durable reward, deck persistence, stable boss portraits, landscape gate, printed card descriptions, no normal Undo, no debug hook and no page errors.');
}finally{await browser.close();}
