/** Production-only smoke: no source imports or development hooks in the browser. */
import { launch, settleMotion } from './browser.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { skipCampaignDialogue } from './story-fixtures.mjs';
import { holdCard, manualRotationBrowser, resizePhone, rotateForDuel } from './phone-fixtures.mjs';
import { checkCampaignMotion } from './campaign-motion.mjs';
const base=process.argv[2];if(!base)throw new Error('Pass the published /play/ URL');
const browser=await launch();const page=await browser.newPage({viewport:{width:1440,height:950}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const progress=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('convergence.progress.v4')));
try{
 await mkdir('../.preview/release',{recursive:true});
 await page.goto(base,{waitUntil:'domcontentloaded'});
 await page.evaluate(()=>{localStorage.clear();localStorage.setItem('convergence.progress.v2','{"unlocked":216}');localStorage.setItem('convergence.save.v27','{"version":27}');localStorage.setItem('sound-test-preference','preserved');});
 await page.reload();await page.locator('.title-screen').waitFor();
 assert.equal(await page.locator('.hero-power-trigger').count(),0);
 assert.equal((await progress()).unlockedIds.length,30);assert.equal((await progress()).completedChapters,0);
 assert.equal(await page.locator('.orbit-choice,.daily-pack-trigger').count(),0);
 assert.equal(await page.evaluate(()=>localStorage.getItem('convergence.progress.v2')),null);
 assert.equal(await page.evaluate(()=>localStorage.getItem('sound-test-preference')),'preserved');
 await page.keyboard.type('Ross');await page.locator('.duel-trigger').click();
 assert.equal(await page.locator('.campaign-chapter').count(),20);
 await page.locator('[data-chapter="1"] button').click();
 await page.locator('[data-story-key]').waitFor(); await skipCampaignDialogue(page);
 await page.locator('.duel-intro').waitFor({state:'detached',timeout:25000});
 await page.locator('.mulligan-panel button.primary').click();
 await page.locator('.boss-portrait').evaluate(img=>img.decode());
 assert.equal(await page.evaluate(()=>typeof window.__debug),'undefined');
 assert((await page.locator('.campaign-hero .hero-name strong').textContent()).includes('GLaDOS'));
 await page.getByRole('button',{name:'Open Star Chart for GLaDOS',exact:true}).click();
 assert(await page.getByRole('dialog',{name:'GLaDOS Star Chart',exact:true}).isVisible());
 await page.getByLabel('Close Star Chart').click();
 await page.screenshot({path:'../.preview/release/live-chapter-one.png'});
 await page.getByRole('button',{name:'DEV tools',exact:true}).click();
 await page.locator('.developer-search input').fill('John Wick');await page.locator('.developer-card-row').first().click();
 await page.getByRole('button',{name:'I win',exact:true}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('convergence.progress.v4')).completedChapters===1);
 assert.equal((await progress()).unlockedIds.length,40);assert.equal((await progress()).pendingRewards.length,10);
 await page.reload();await page.locator('[data-story-stage="defeat"]').waitFor();await skipCampaignDialogue(page);await page.locator('.pack-veil').waitFor();assert.equal((await progress()).pendingRewards.length,10);
 await settleMotion(page);
 for(let hit=0;hit<8;hit++){const box=page.locator('.pack-box:not(.is-charged)');if(!await box.isVisible())break;const label=await box.getAttribute('aria-label');await box.click({force:true});await page.waitForFunction(label=>document.querySelector('.pack-box')?.getAttribute('aria-label')!==label,label);}
 await page.locator('.pack-collect:not([disabled])').click({timeout:25000});
 await page.locator('.deck-trigger').click();await page.getByRole('button',{name:'Remove John Wick from deck',exact:true}).click();
 await page.getByLabel('Search the gallery').fill('GLaDOS');await page.getByRole('button',{name:'Add GLaDOS',exact:true}).click();
 assert.equal((await progress()).playerDeck.length,30);assert((await progress()).playerDeck.includes('c104'));
 await page.getByRole('button',{name:'Choose hero power',exact:true}).click();
 assert.equal(await page.locator('.gallery-power-picker .hero-power-menu-card:not(:disabled)').count(),1);
 await page.locator('.gallery-power-picker .hero-power-menu-card').filter({hasText:'Mend Core'}).click();
 assert.equal((await progress()).selectedHeroPower,'core_heal');
 await page.reload();assert((await progress()).playerDeck.includes('c104'));assert.equal((await progress()).pendingRewards.length,0);
 await page.locator('.duel-trigger').click();assert(await page.locator('[data-chapter="2"] button').isEnabled());
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'../.preview/release/live-campaign-mobile.png'});
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await manualRotationBrowser(phoneContext);
 const phone=await phoneContext.newPage();phone.on('pageerror',error=>errors.push(error.message));
 await phone.goto(base,{waitUntil:'domcontentloaded'});
 await phone.locator('.duel-trigger').tap();await checkCampaignMotion(phone);
 await phone.locator('[data-chapter="1"] button').tap();await skipCampaignDialogue(phone);
 await rotateForDuel(phone,390,844);
 await phone.locator('.duel-intro').dblclick();await phone.locator('.duel-intro').waitFor({state:'detached',timeout:25000});
 await phone.locator('.mulligan-panel button.primary').tap();
 assert.equal(await phone.evaluate(()=>typeof window.__debug),'undefined');
 assert.equal(await phone.locator('.mobile-card-read').count(),0);
 const hand=phone.locator('.hand-card').first();const handLabel=await hand.getAttribute('aria-label');
 const cardName=handLabel.split(',')[0];const cardsBefore=await phone.locator('.hand-card').count();
 await holdCard(phone,hand,`Read ${cardName}`);
 await phone.screenshot({path:'../.preview/release/live-phone-reader.png'});
 await phone.getByRole('button',{name:'Close card reader',exact:true}).tap();
 assert.equal(await phone.locator('.hand-card').count(),cardsBefore,'Published reader played its card');
 await phone.getByRole('button',{name:'Duel menu',exact:true}).tap();
 assert.equal(await phone.getByRole('button',{name:'Undo last action',exact:true}).count(),0);
 await phone.getByRole('button',{name:'Duel menu',exact:true}).tap();
 const turnBefore=await phone.locator('.deck-pile em').textContent();
 await resizePhone(phone,390,844);await phone.getByRole('dialog',{name:'Landscape mode required',exact:true}).waitFor();
 await phone.screenshot({path:'../.preview/release/live-phone-rotate.png'});
 await phone.keyboard.press('Space');await phone.waitForTimeout(1100);
 assert.equal(await phone.locator('.deck-pile em').textContent(),turnBefore,'Portrait gate allowed a turn to advance');
 await resizePhone(phone,844,390);await phone.getByRole('dialog',{name:'Landscape mode required',exact:true}).waitFor({state:'detached'});
 await phone.screenshot({path:'../.preview/release/live-phone-duel.png'});
 await phoneContext.close();
 assert.deepEqual(errors,[]);
 console.log('PASS live production: old-save reset, campaign, durable reward, deck persistence, stable boss portraits, landscape gate, native long press, no normal Undo, no debug hook and no page errors.');
}finally{await browser.close();}
